<?php

/**
 * Created by PhpStorm.
 * User: Danish
 * Date: 3/6/2021
 * Time: 10:36 PM
 */
class Three extends Two {
    function test() {
        echo "function test() is called of class Three <br>" . PHP_EOL;
    }

    function anotherTest() {
        parent::func();
    }

    function classThreeMethod() {
        echo "function classThreeMethod() is called of class Three <br>" . PHP_EOL;
    }

    function jack() {
        echo "function jack() is called of class Three <br>";
    }

    function accessParent() {
        parent::accessParent(); // TODO: Change the autogenerated stub
    }

    function oneFunction() {
        parent::oneFunction(); // TODO: Change the autogenerated stub
    }

}